name: Test index.html title

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering of the workflow

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  generate-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: npm_installer
        run: npm install jsdom

      - name: the_copy_cat
        run: |
          node -e "
          const fs = require('fs');
          const { JSDOM } = require('jsdom');
          
          // Load index.html
          const htmlContent = fs.readFileSync('index.html', 'utf-8');
          const dom = new JSDOM(htmlContent);
          
          // Extract <title> and first <p> as description
          const title = dom.window.document.querySelector('title')?.textContent || 'My Project';
          const description = dom.window.document.querySelector('p')?.textContent || 'Description not available.';
          
          // Generate README content
          const readmeContent = \`# \${title}\n\n\${description}\n\nThis README was generated automatically from index.html.\`;
          
          // Write to README.md
          fs.writeFileSync('README.md', readmeContent);
          "
      - name: checking_title
        run: |
          node -e "
          const fs = require('fs');
          const { JSDOM } = require('jsdom');
          
          // Load index.html
          const htmlContent = fs.readFileSync('index.html', 'utf-8');
          const dom = new JSDOM(htmlContent);

          // Extract <title> and first <p> as description
          const title = dom.window.document.querySelector('title')?.textContent;

          if(false){
           exit 0;
          }else{
          exit 1;
          }
          "